name: Release-GitHub-Page

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install && npm run build
        env:
          VITE_GAS_API_URL: ${{ secrets.VITE_GAS_API_URL }}
